### ISSUE TITLE
قومیت‌ها؟

### ISSUE THREAD

**Issue by aminvakil** [amirshnll/Persian-Swear-Words#1]
چرا قومیت‌ها هم در لیست قرار دارند؟

در خیلی از موارد لزوما دلیل بر توهین نیستند.

https://github.com/amirshnll/Persian-Swear-Words/blob/5c7f427e87ace71b831feae7c7d72d13ab1572e4/data.json#L210-L212

**Comment by amirshnll** [comment]
@aminvakil 
در حالت عادی توهین نیستند ولی توی کاربردی که من نیازشون داشتم باید این موارد هم فیلتر میشدن برای همین توی فایل موجود هست و با توجه به نیاز هر پروژه این دیتاست باید کم و زیاد بشه
