### ISSUE TITLE
تکرار کلمات چند بخشی

### ISSUE THREAD

**Issue by Hessam-Koucheki** [amirshnll/Persian-Swear-Words#14]
سلام و خسته نباشید
ببخشید برای کلمات چند بخشی نظیر` (دیوث، دیوث خان، دیوث هستی، دیوث بزرگ)` فقط مورد اول کافی نیست؟
منظورم اینه که سه کلمه بعدی همشون کلمه `دیوث` رو دارن، پس وقتی داره سرچ میشه همون کلمه‌ی` (دیوث)` پیدا میشه، و نیازی نیست که ترکیبات اون کلمه توی لیست تکرار بشه.

یعنی لیست `(دیوث، دیوث خان، دیوث هستی، دیوث بزرگ)`  میتونه به لیست` (دیوث)` تبدیل بشه و همچنان کار کنه

البته منظورم کلمات چسبیده مثل `( دیوث، دیوثی، دیوثک)` نیست.

**Comment by amirshnll** [comment]
کتابخونه توسط چندین نفر تکمیل شده هر فرد یه بخشی اضافه کرده اگر چیزی کم یا زیاد هست شما اصلاح کنید.
<br />
در مورد چندبخشی ها هم درسته همون بخش اولش فیلتر بشه کافیه حتما اصلاح میکنم
