### ISSUE TITLE
Python Installation

### ISSUE THREAD

**Issue by Saba-Heydaridoost** [amirshnll/Persian-Swear-Words#23]
Hello, I would like to know how to install the package in python?

**Comment by amirshnll** [comment]
Hey @Saba-Heydaridoost 
In this repository, I have a [Python function](https://github.com/amirshnll/Persian-Swear-Words/blob/master/PersianSwear.py) that you can utilize in your project, or you can develop a personal Python package. Previously, @mmdbalkhi created it in another repository. You can access it using the following link: https://github.com/mmdbalkhi/Sansorchi.

PS: I have not tested this package, and I cannot recommend it. However, you are welcome to check it out and use it.

**Comment by Saba-Heydaridoost** [comment]
Thank you!
