### ISSUE TITLE
Time complexity

### ISSUE THREAD

**Issue by hysapp** [amirshnll/Persian-Swear-Words#24]
What is the time complexity in a `n` letter text?
Does it open and close the data file every time?
I need to use in real time chat filter with thousands of users. Is it effective enough in this case?

**Comment by amirshnll** [comment]
Hey @hysapp ,
If you have a big enterprise project, I recommend writing custom and personalized code and utilizing JSON dataset. I do not test repository codes in enterprise chats or other real-time systems.
