### ISSUE TITLE
Duplicate Word

### ISSUE THREAD

**Issue by thinker-amir** [amirshnll/Persian-Swear-Words#4]
You have some duplicate words in data.json file.

**Comment by RamtinA** [comment]
> 
> 
> You have some duplicate words in data.json file.

You are right I just removed duplicates and the correct number of unique words is 263.

**Comment by amirshnll** [comment]
> > You have some duplicate words in data.json file.
> 
> You are right I just removed duplicates and the correct number of unique words is 263.

merge request ?!
