### ISSUE TITLE
Typo in words

### ISSUE THREAD

**Issue by IAmTalas** [amirshnll/Persian-Swear-Words#7]
https://github.com/amirshnll/Persian-Swear-Words/blob/e5eca28024e972ffb1a1eb688b127168e0d855fa/data.json#L209
https://github.com/amirshnll/Persian-Swear-Words/blob/e5eca28024e972ffb1a1eb688b127168e0d855fa/data.json#L8

 Hi, I think there is two **typos** in these words

**Comment by amirshnll** [comment]
@IAmTalas 
thank you 👍
